# Data Encoding

## Label Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# Construct LabelEncoder object
encoder = LabelEncoder()

# Use fit() and transform()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [6]:
encoder.classes_ # 0,1,2,3,4

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [7]:
# decoding
encoder.inverse_transform([4,5,2,0,1,1,3,3])

array(['전자레인지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'],
      dtype='<U5')

## One-Hot Encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고', '전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

items = np.array(items).reshape(-1,1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [11]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

# Feature Scaling and Normalization

## StandardScaler

- Average value = 0
- Variance = 1

In [17]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print("Average")
print(iris_df.mean())
print("Variance")
print(iris_df.var())

Average
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
Variance
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [19]:
from sklearn.preprocessing import StandardScaler

# Construct StandardScaler object
scaler = StandardScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('Average')
print(iris_df_scaled.mean())
print('Variance')
print(iris_df_scaled.var())

Average
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
Variance
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


## MinMaxScaler

- Range : 0 ~ 1

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('min')
print(iris_df_scaled.min())
print('max')
print(iris_df_scaled.max())

min
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
max
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


## Caution

In [23]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0, 6).reshape(-1,1)

scaler = MinMaxScaler()

# fit() -> train_array's range is set to 0 - 10
scaler.fit(train_array)

# transform() -> train_array's range is set to 0 - 1
train_scaled = scaler.transform(train_array)

print('original train_array:', np.round(train_array.reshape(-1),2))
print('Scaled train_array:',np.round(train_scaled.reshape(-1),2))



original train_array: [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [24]:
# Second fit() -> set to 0 - 5
scaler.fit(test_array)

test_scaled = scaler.transform(test_array)

print('original test_array:', np.round(test_array.reshape(-1),2))
print('Scaled test_array:',np.round(test_scaled.reshape(-1),2))

original test_array: [0 1 2 3 4 5]
Scaled test_array: [0.  0.2 0.4 0.6 0.8 1. ]


!! Scaled train_array's range != Scaled test_array's range !!

In [26]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('original train_array:', np.round(train_array.reshape(-1),2))
print('Scaled train_array:',np.round(train_scaled.reshape(-1),2))

# Do not use fit() again
test_scaled = scaler.transform(test_array)
print('original test_array:', np.round(test_array.reshape(-1),2))
print('Scaled test_array:',np.round(test_scaled.reshape(-1),2))

original train_array: [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
original test_array: [0 1 2 3 4 5]
Scaled test_array: [0.  0.1 0.2 0.3 0.4 0.5]
